swagger: '2.0'
info:
  title: ArgentBank API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/account/{accountId}/transactions:
    get:
      security:
      - Bearer: []
      tags:
      - Account Module
      produces:
        - application/json
      summary: Get account transactions
      description: Retrieve acounts list
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        type: string
      - in: path
        name: accountId
        type: integer
        required: true
        description: Numeric ID of the account to get
      - in: query
        name: limit
        type: integer
        description: The numbers of items to return
      - in: query
        name: offset
        type: integer
        required: false
        description: The number of items to skip before starting to collect the result set
      - in: query
        name: month
        type: string
        format: MM:YYYY
        description: The month of transactions to get
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            type: object
            properties:
              status:
                type: integer
              body:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions:
    get:          
      security:
      - Bearer: []
      tags:
      - Transactions
      produces:
        - application/json
      summary: Get a specific transaction
      description: Retrieve a specific user transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        type: string
      responses:
        '200':
          description: User accounts retrieved successully
          schema:
            type: object
            properties:
              status:
                type: integer
              body:
                type: object
                properties:
                  transaction:
                    $ref: '#/definitions/ApiResponse'
                      

        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: transactions
      description: API for transactions
      parameters:
        - in: header
          name: Autorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transactions received
          schema:
            $ref: '#/definitions/AllTransactions'
        '400':
          description: Invalid Token
        '500':
          description: Internal Server Error
  /user/transactions/id:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Transactions specifics
      description: API for transactions specifics
      parameters:
        - in: header
          name: Autorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: id
          description: id of the transactions
          required: true
          schema:
            $ref: '#/definitions/Details'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Add/Change/Delete details
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction attribute
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction saved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Field
        '500':
          description: Internal Server Error
    get:          
      security:
      - Bearer: []
      tags:
      - Transactions
      produces:
        - application/json
      summary: Get a specific transaction
      description: Retrieve a specific user transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        type: string
      responses:
        '200':
          description: User accounts retrieved successully
          schema:
            type: object
            properties:
              status:
                type: integer
              body:
                type: object
                properties:
                  transaction:
                    $ref: '#/definitions/ApiResponse'
                      

        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Details:
    properties:
      id:
        type: string
        description: transaction id
  ApiResponse:
    type: object
    properties:
      description:
        type: string
  AllTransactions:
    type: object
    properties:
      id:
        type: string
      amount:
        type: string
      date:
        type: string
  UpdateTransaction:
    type: object
    properties:
      id:
        type: string
      description:
        type: string
